name: "Release Trigger Action"

description: "A reusable action to handle version release and build information"
# all inputs are required 
inputs:
  gpg_private_key:
    description: "GPG secret key for signing commits and tags"
    required: true
  gpg_passphrase:
    description: "Passphrase for the GPG key"
    required: true
  git_user_email:
    description: "Email for git commits"
    required: true
  git_username:
    description: "Username for git commits"
    required: true
  git_token:
    description: "GitHub token for accessing GitHub API"
    required: true
  version_file_path:
    description: "Path to the version file"
    required: true
  release_branch:
    description: "Name of the release branch"
    required: true
  bump_script:
    description: "Path to the bump script"
    required: true
  release_sha:
    description: "Release SHA"
    required: false
  working_directory:
    description: "Working directory"
    required: true
    default: "."
outputs:
  release_version:
    description: "The version of the release"
    value: ${{ steps.bump-version.outputs.version }}
  pr_log:
    description: "Log of pull requests"
    value: ${{ steps.changelog.outputs.changelog }}
  build_number:
    description: "The build number"
    value: ${{ steps.build-number.outputs.build_number }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.7

    - name: setup node
      uses: actions/setup-node@v4.0.3
      with:
        node-version: "20.x"

    - name: Install GitHub CLI
      shell: bash
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6.1.0
      with:
        gpg_private_key: ${{ inputs.gpg_private_key }}
        passphrase: ${{ inputs.gpg_passphrase }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_tag_gpgsign: true

    - name: setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9.6.0
        run_install: false

    - name: set pnpm cache
      uses: actions/cache@v4.0.2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: pnpm install and build
      shell: bash
      run: pnpm install --no-frozen-lockfile

    - name: Global Git config
      shell: bash
      run: |
        git config --global user.email "${{ inputs.git_user_email }}"
        git config --global user.name "${{ inputs.git_username }}"

    - name: bump version
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      id: bump-version
      run: |
        pnpm ${{ inputs.bump_script }}
        version=$(jq -r '.version' package.json)
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "current version $version"

    - name: Push to protected branch
      uses: CasperWA/push-protected@v2.16.0
      with:
        token: ${{ inputs.git_token }}
        branch: ${{ inputs.release_branch }}
        tags: true
        force: true
        acceptable_conclusions: success
    - name: Generate Changelog
      shell: bash
      id: changelog
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        # Get the previous tag, defaulting to the initial commit if no tags exist
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)

        # Get the date of the previous tag
        PREVIOUS_TAG_DATE=$(git log -1 --format=%aI $PREVIOUS_TAG)

        # Fetch merged PRs since the previous tag
        PR_LOG=$(gh pr list \
          --repo ${{ github.repository }} \
          --search "is:merged merged:>$PREVIOUS_TAG_DATE" \
          --json number,title,author,mergeCommit \
          --jq '
            [.[] | {
              number: .number,
              title: .title,
              author: .author.login,
              sha: .mergeCommit.oid
            }]
          '
        )
        # Function to get commits for a PR
        get_pr_commits() {
          local pr_number=$1
          gh pr view $pr_number --repo ${{ github.repository }} --json commits --jq '
            .commits | map("  - " + .messageHeadline) | join("\n")
          '
        }

        # Generate changelog
        CHANGELOG="Changes since $PREVIOUS_TAG:\n"
        while read -r pr; do
          pr_number=$(echo $pr | jq -r '.number')
          pr_title=$(echo $pr | jq -r '.title')
          pr_author=$(echo $pr | jq -r '.author')
          pr_sha=$(echo $pr | jq -r '.sha')
          
          CHANGELOG+="- $pr_title (#$pr_number) by @$pr_author\n"
          commits=$(get_pr_commits $pr_number)
          CHANGELOG+="$commits\n\n"
        done < <(echo "$PR_LOG" | jq -c '.[]')

        # Escape the changelog content for GitHub Actions output
        CHANGELOG_ESCAPED="${CHANGELOG//'%'/'%25'}"
        CHANGELOG_ESCAPED="${CHANGELOG_ESCAPED//$'\n'/'%0A'}"
        CHANGELOG_ESCAPED="${CHANGELOG_ESCAPED//$'\r'/'%0D'}"

        # Output to GITHUB_OUTPUT
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG_ESCAPED" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        # Display the changelog in the action logs
        echo -e "$CHANGELOG"
   
    - name: Release Version
      shell: bash
      id: release-version
      run: |
        echo "release-version=$(jq -r '.version' ${{inputs.version_file_path}} )" >> $GITHUB_OUTPUT
    - name: get build number
      id: build-number
      shell: bash
      run: |
        echo "extracting build number"
        VALUE=$(cat .github/build.yml | xargs)
        echo "build_number=${VALUE}" >> $GITHUB_OUTPUT
        echo "build_number=${VALUE}"
    - name: Log all variables
      shell: bash
      run: |
        echo "release-version=${{ steps.release-version.outputs.release-version }}"
        echo "build-number=${{ steps.build-number.outputs.build_number }}"
        echo "pr-log=${{ steps.pr-log.outputs.pr-log }}"
        echo "pr-logs=${{ steps.pr-log.outputs.pr-log }}"
